# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab_10_design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 900))
        MainWindow.setStyleSheet("background-color: rgb(232, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1578, 882))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(7, 7, 10, 10)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.scene = QtWidgets.QGraphicsScene()
        self.scene.setSceneRect(5, 11, 1195, 869)
        self.canvas = QtWidgets.QGraphicsView(self.scene, self.widget)
        self.canvas.setMinimumSize(QtCore.QSize(1200, 880))
        self.canvas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.canvas.setObjectName("canvas")
        self.gridLayout.addWidget(self.canvas, 0, 0, 1, 1)
        self.splitter_9 = QtWidgets.QSplitter(self.widget)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setHandleWidth(19)
        self.splitter_9.setObjectName("splitter_9")
        self.color_box = QtWidgets.QComboBox(self.splitter_9)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.color_box.setFont(font)
        self.color_box.setStyleSheet("selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(255, 255, 255);")
        self.color_box.setObjectName("color_box")
        self.color_box.addItem("")
        self.color_box.addItem("")
        self.color_box.addItem("")
        self.color_box.addItem("")
        self.color_box.addItem("")
        self.color_box.addItem("")
        self.color_box.addItem("")
        self.color_box.addItem("")
        self.func_box = QtWidgets.QComboBox(self.splitter_9)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.func_box.setFont(font)
        self.func_box.setStyleSheet("selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(255, 255, 255);")
        self.func_box.setObjectName("func_box")
        self.func_box.addItem("")
        self.func_box.addItem("")
        self.func_box.addItem("")
        self.func_box.addItem("")
        self.func_box.addItem("")
        self.func_box.addItem("")
        self.func_box.addItem("")
        self.func_box.addItem("")
        self.limits_lbl = QtWidgets.QLabel(self.splitter_9)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.limits_lbl.setFont(font)
        self.limits_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.limits_lbl.setObjectName("limits_lbl")
        self.splitter = QtWidgets.QSplitter(self.splitter_9)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_13 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setText("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.from_lbl = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.from_lbl.setFont(font)
        self.from_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.from_lbl.setObjectName("from_lbl")
        self.to_lbl = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.to_lbl.setFont(font)
        self.to_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.to_lbl.setObjectName("to_lbl")
        self.step_lbl = QtWidgets.QLabel(self.splitter)
        self.step_lbl.setMaximumSize(QtCore.QSize(98, 16777215))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.step_lbl.setFont(font)
        self.step_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.step_lbl.setObjectName("step_lbl")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(14)
        self.splitter_2.setObjectName("splitter_2")
        self.x_limit_lbl = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.x_limit_lbl.setFont(font)
        self.x_limit_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.x_limit_lbl.setObjectName("x_limit_lbl")
        self.x_from_entry = QtWidgets.QDoubleSpinBox(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.x_from_entry.setFont(font)
        self.x_from_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.x_from_entry.setDecimals(1)
        self.x_from_entry.setMinimum(-100.0)
        self.x_from_entry.setMaximum(100.0)
        self.x_from_entry.setSingleStep(0.1)
        self.x_from_entry.setObjectName("x_from_entry")
        self.x_to_entry = QtWidgets.QDoubleSpinBox(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.x_to_entry.setFont(font)
        self.x_to_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.x_to_entry.setDecimals(1)
        self.x_to_entry.setMinimum(-100.0)
        self.x_to_entry.setMaximum(100.0)
        self.x_to_entry.setSingleStep(0.1)
        self.x_to_entry.setObjectName("x_to_entry")
        self.x_step_entry = QtWidgets.QDoubleSpinBox(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.x_step_entry.setFont(font)
        self.x_step_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.x_step_entry.setDecimals(1)
        self.x_step_entry.setMinimum(-100.0)
        self.x_step_entry.setMaximum(100.0)
        self.x_step_entry.setSingleStep(0.1)
        self.x_step_entry.setObjectName("x_step_entry")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setHandleWidth(14)
        self.splitter_3.setObjectName("splitter_3")
        self.z_limit_lbl = QtWidgets.QLabel(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.z_limit_lbl.setFont(font)
        self.z_limit_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.z_limit_lbl.setObjectName("z_limit_lbl")
        self.z_from_entry = QtWidgets.QDoubleSpinBox(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.z_from_entry.setFont(font)
        self.z_from_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.z_from_entry.setDecimals(1)
        self.z_from_entry.setMinimum(-100.0)
        self.z_from_entry.setMaximum(100.0)
        self.z_from_entry.setSingleStep(0.1)
        self.z_from_entry.setObjectName("z_from_entry")
        self.z_to_entry = QtWidgets.QDoubleSpinBox(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.z_to_entry.setFont(font)
        self.z_to_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.z_to_entry.setDecimals(1)
        self.z_to_entry.setMinimum(-100.0)
        self.z_to_entry.setMaximum(100.0)
        self.z_to_entry.setSingleStep(0.1)
        self.z_to_entry.setObjectName("z_to_entry")
        self.z_step_entry = QtWidgets.QDoubleSpinBox(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.z_step_entry.setFont(font)
        self.z_step_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.z_step_entry.setDecimals(1)
        self.z_step_entry.setMinimum(-100.0)
        self.z_step_entry.setMaximum(100.0)
        self.z_step_entry.setSingleStep(0.1)
        self.z_step_entry.setObjectName("z_step_entry")
        self.draw_btn = QtWidgets.QPushButton(self.splitter_9)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.draw_btn.setFont(font)
        self.draw_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 74, 135);")
        self.draw_btn.setObjectName("draw_btn")
        self.rotate_lbl = QtWidgets.QLabel(self.splitter_9)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.rotate_lbl.setFont(font)
        self.rotate_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rotate_lbl.setObjectName("rotate_lbl")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setHandleWidth(14)
        self.splitter_4.setObjectName("splitter_4")
        self.x_rotate_lbl = QtWidgets.QLabel(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.x_rotate_lbl.setFont(font)
        self.x_rotate_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.x_rotate_lbl.setObjectName("x_rotate_lbl")
        self.x_rotate_entry = QtWidgets.QDoubleSpinBox(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.x_rotate_entry.setFont(font)
        self.x_rotate_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.x_rotate_entry.setDecimals(0)
        self.x_rotate_entry.setMinimum(-45.0)
        self.x_rotate_entry.setMaximum(45.0)
        self.x_rotate_entry.setSingleStep(1.0)
        self.x_rotate_entry.setObjectName("x_rotate_entry")
        self.x_rotate_btn = QtWidgets.QPushButton(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.x_rotate_btn.setFont(font)
        self.x_rotate_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 74, 135);")
        self.x_rotate_btn.setObjectName("x_rotate_btn")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setHandleWidth(14)
        self.splitter_5.setObjectName("splitter_5")
        self.y_rotate_lbl = QtWidgets.QLabel(self.splitter_5)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.y_rotate_lbl.setFont(font)
        self.y_rotate_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.y_rotate_lbl.setObjectName("y_rotate_lbl")
        self.y_rotate_entry = QtWidgets.QDoubleSpinBox(self.splitter_5)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.y_rotate_entry.setFont(font)
        self.y_rotate_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.y_rotate_entry.setDecimals(0)
        self.y_rotate_entry.setMinimum(-45.0)
        self.y_rotate_entry.setMaximum(45.0)
        self.y_rotate_entry.setSingleStep(1.0)
        self.y_rotate_entry.setObjectName("y_rotate_entry")
        self.y_rotate_btn = QtWidgets.QPushButton(self.splitter_5)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.y_rotate_btn.setFont(font)
        self.y_rotate_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 74, 135);")
        self.y_rotate_btn.setObjectName("y_rotate_btn")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setHandleWidth(14)
        self.splitter_6.setObjectName("splitter_6")
        self.z_rotate_lbl = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.z_rotate_lbl.setFont(font)
        self.z_rotate_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.z_rotate_lbl.setObjectName("z_rotate_lbl")
        self.z_rotate_entry = QtWidgets.QDoubleSpinBox(self.splitter_6)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.z_rotate_entry.setFont(font)
        self.z_rotate_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.z_rotate_entry.setDecimals(0)
        self.z_rotate_entry.setMinimum(-45.0)
        self.z_rotate_entry.setMaximum(45.0)
        self.z_rotate_entry.setSingleStep(1.0)
        self.z_rotate_entry.setObjectName("z_rotate_entry")
        self.z_rotate_btn = QtWidgets.QPushButton(self.splitter_6)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.z_rotate_btn.setFont(font)
        self.z_rotate_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 74, 135);")
        self.z_rotate_btn.setObjectName("z_rotate_btn")
        self.scale_lbl = QtWidgets.QLabel(self.splitter_9)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.scale_lbl.setFont(font)
        self.scale_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.scale_lbl.setObjectName("scale_lbl")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setHandleWidth(14)
        self.splitter_7.setObjectName("splitter_7")
        self.scale_lbl_2 = QtWidgets.QLabel(self.splitter_7)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.scale_lbl_2.setFont(font)
        self.scale_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.scale_lbl_2.setObjectName("scale_lbl_2")
        self.scale_entry = QtWidgets.QDoubleSpinBox(self.splitter_7)
        self.scale_entry.setMaximumSize(QtCore.QSize(97, 16777215))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.scale_entry.setFont(font)
        self.scale_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scale_entry.setDecimals(1)
        self.scale_entry.setMinimum(-100.0)
        self.scale_entry.setMaximum(100.0)
        self.scale_entry.setSingleStep(0.1)
        self.scale_entry.setObjectName("scale_entry")
        self.scale_btn = QtWidgets.QPushButton(self.splitter_7)
        self.scale_btn.setMinimumSize(QtCore.QSize(182, 0))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.scale_btn.setFont(font)
        self.scale_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(32, 74, 135);")
        self.scale_btn.setObjectName("scale_btn")
        self.label_14 = QtWidgets.QLabel(self.splitter_9)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setText("")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setHandleWidth(19)
        self.splitter_8.setObjectName("splitter_8")
        self.clear_btn = QtWidgets.QPushButton(self.splitter_8)
        self.clear_btn.setMinimumSize(QtCore.QSize(166, 0))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(78, 154, 6);")
        self.clear_btn.setObjectName("clear_btn")
        self.exit_btn = QtWidgets.QPushButton(self.splitter_8)
        self.exit_btn.setMinimumSize(QtCore.QSize(166, 0))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("background-color: rgb(164, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.exit_btn.setObjectName("exit_btn")
        self.gridLayout.addWidget(self.splitter_9, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Алгоритм плавающего горизонта"))
        self.color_box.setItemText(0, _translate("MainWindow", "Выбор цвета"))
        self.color_box.setItemText(1, _translate("MainWindow", "Красный"))
        self.color_box.setItemText(2, _translate("MainWindow", "Синий"))
        self.color_box.setItemText(3, _translate("MainWindow", "Чёрный"))
        self.color_box.setItemText(4, _translate("MainWindow", "Зеленый"))
        self.color_box.setItemText(5, _translate("MainWindow", "Горчичный"))
        self.color_box.setItemText(6, _translate("MainWindow", "Фиолетовый"))
        self.color_box.setItemText(7, _translate("MainWindow", "Белый"))
        self.func_box.setItemText(0, _translate("MainWindow", "Выбор функции"))
        self.func_box.setItemText(1, _translate("MainWindow", "sin^2(x) + cos^2(z)"))
        self.func_box.setItemText(2, _translate("MainWindow", "x^2 / 20 - z^2 / 20"))
        self.func_box.setItemText(3, _translate("MainWindow", "exp(sin(sqrt(x^2 + z^2)))"))
        self.func_box.setItemText(4, _translate("MainWindow", "x^2 / 20 + z^2 / 20"))
        self.func_box.setItemText(5, _translate("MainWindow", "x * z / 25"))
        self.func_box.setItemText(6, _translate("MainWindow", "sqrt(x^2 + z^2 + 25)"))
        # self.func_box.setItemText(7, _translate("MainWindow", "Белый"))
        self.limits_lbl.setText(_translate("MainWindow", "Пределы:"))
        self.from_lbl.setText(_translate("MainWindow", "От:"))
        self.to_lbl.setText(_translate("MainWindow", "До:"))
        self.step_lbl.setText(_translate("MainWindow", "Шаг:"))
        self.x_limit_lbl.setText(_translate("MainWindow", "Х:"))
        self.z_limit_lbl.setText(_translate("MainWindow", "Z:"))
        self.draw_btn.setText(_translate("MainWindow", "Применить"))
        self.rotate_lbl.setText(_translate("MainWindow", "Поворот:"))
        self.x_rotate_lbl.setText(_translate("MainWindow", "Х:"))
        self.x_rotate_btn.setText(_translate("MainWindow", "Повернуть"))
        self.y_rotate_lbl.setText(_translate("MainWindow", "Y:"))
        self.y_rotate_btn.setText(_translate("MainWindow", "Повернуть"))
        self.z_rotate_lbl.setText(_translate("MainWindow", "Z:"))
        self.z_rotate_btn.setText(_translate("MainWindow", "Повернуть"))
        self.scale_lbl.setText(_translate("MainWindow", "Масштабирование:"))
        self.scale_lbl_2.setText(_translate("MainWindow", "К:"))
        self.scale_btn.setText(_translate("MainWindow", "Применить"))
        self.clear_btn.setText(_translate("MainWindow", "Очистить"))
        self.exit_btn.setText(_translate("MainWindow", "Выход"))
